### PR TITLE
Fix ReadUBits(32) masking out all bits. Thanks to @in0finite

### LINKED ISSUE #37: Pawn position is outside of buy-zone during freeze time
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

Sometimes, during freeze time pawn is placed outside of buy-zone.

To reproduce:

Go to: https://csunity-5172f.web.app/
Click Open -> Ok -> Select `navi-javelins-vs-9-pandas-fearless-m1-mirage.dem` -> Click Pause

Observe player "victoria" on the middle of screen. If you look around, you'll see his teammates are too far away from him. 

Once the round starts, his position will be correct.

His position coordinates are again 1024. You can see that in Inspector (but converted to meters, it will be 32).

### Code to reproduce

_No response_

### Affected demos

navi-javelins-vs-9-pandas-fearless-m1-mirage.dem

### PR DESCRIPTION
**Pull request by saul**
Fixes #37

### CODE REVIEW

File: src/DemoFile/BitBuffer.cs [hunk 1]
```diff
@@ -28,7 +41,7 @@ public uint ReadUBits(int numBits)
     {
```
Comment (in0finite) [inline src/DemoFile/BitBuffer.cs:41]: Can you please add a safeguard here, so it's easier to catch similar bugs :
```
#if DEBUG
if (numBits > 32 || numBits < 0)
    throw ...;
#endif
```

**Comment by in0finite** [comment]
Could you also add a safeguard after reading all entities from BitBuffer [here](https://github.com/saul/demofile-net/blob/f8648e3ffcee2437bdcb51d94e76fc985991508c/src/DemoFile/DemoParser.Entities.cs#L390), to make sure everything is read from it:

```
if (entityBitBuffer.RemainingBytes >= 4)
    throw "not all data read";
```

File: src/DemoFile/BitBuffer.cs (hunk 1 above)
Comment (saul) [reply src/DemoFile/BitBuffer.cs:41]: This will throw as the code is already written

Comment (in0finite) [reply src/DemoFile/BitBuffer.cs:41]: Maybe I am missing something, but if the code goes into `else` branch and if  `numBits` is 50 and `_bitsAvail` is 32, it will not throw, but instead decrease `numBits` to 18.

Anyways, it's not intuitive as it is, so adding `Debug.Assert()` would not hurt.
